version: "3.9"
services:
  node:
    build:
      context: ./docker/node
    tty: true
    volumes:
      - ./src:/var/www/src
      - node_modules:/var/www/src/node_modules
    ports:
      - "3000:3000"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - "./docker/redis:/data"

volumes:
  node_modules:
